apiVersion: v1
kind: Namespace
metadata:
  name: obmovies
---

apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  namespace: obmovies
  name: ds-priority
value: 1000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "DaemonSet services."
---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: obmovies
  name: obmovies
spec:
  selector:
      matchLabels:
        name: obmovies
  template:
    metadata:
      labels:
        name: obmovies
    spec:
      priorityClassName: ds-priority
      containers:
      - name: obmovies
        image: obmovies_app
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        args:
        - python
        - run.py
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi

